# Autogenerated with SMOP version 
# smop-0.26.2/smop/main.py LU.m

from __future__ import division
try:
    from runtime import *
except ImportError:
    from smop.runtime import *

A=[[1,5,3,5],[2,5,6,7],[9,0,3,4],[9,4,7,6]]
R,C=size(A,nargout=2)
for i in arange_(1,R).reshape(-1):
    L[i,1]=A(i,1)
    U[i,i]=1
for j in arange_(2,R).reshape(-1):
    U[1,j]=A(1,j) / L(1,1)
for i in arange_(2,R).reshape(-1):
    for j in arange_(2,i).reshape(-1):
        L[i,j]=A(i,j) - L(i,arange_(1,j - 1)) * U(arange_(1,j - 1),j)
    for j in arange_(i + 1,R).reshape(-1):
        U[i,j]=(A(i,j) - L(i,arange_(1,i - 1)) * U(arange_(1,i - 1),j)) / L(i,i)
